# Generated by Django 6.0.1 on 2026-01-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('RECEIVED', 'Przyjęte'), ('IN_PROGRESS', 'W toku'), ('WAITING_FOR_PARTS', 'Czeka na części'), ('READY', 'Gotowe do odbioru'), ('COMPLETED', 'Zakończone'), ('CANCELED', 'Anulowane')], db_index=True, default='NEW', max_length=20)),
                ('estimated_completion_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
