# Generated by Django 6.0.1 on 2026-01-25 18:52

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_serviceorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='order_number',
            field=models.CharField(db_index=True, default=orders.models.generate_order_number, editable=False, max_length=20, unique=True),
        ),
    ]
