# Generated by Django 6.0.1 on 2026-01-25 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_serviceorder_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Wewnętrzny'), ('PUBLIC', 'Publiczny')], db_index=True, default='INTERNAL', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.serviceorder')),
            ],
        ),
    ]
