# Generated by Django 6.0.1 on 2026-01-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.serviceorder'),
        ),
    ]
