# Generated by Django 6.0.1 on 2026-01-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auditlog_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STATUS_CHANGED', 'Zmiana statusu'), ('COMMENT_ADDED', 'Dodanie komentarza'), ('ESTIMATE_SET', 'Ustawienie estymacji'), ('ORDER_CANCELED', 'Anulowanie zlecenia'), ('ORDER_CREATED', 'Utworzenie zlecenia')], db_index=True, max_length=50),
        ),
    ]
