# Generated by Django 6.0.1 on 2026-01-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_snapshot', models.CharField(max_length=200)),
                ('base_price_min_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_max_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.serviceorder')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name_snapshot', models.CharField(max_length=200)),
                ('price_delta_min_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_delta_max_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_options', to='orders.serviceoption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='orders.serviceorderitem')),
            ],
        ),
    ]
