# Generated by Django 6.0.1 on 2026-05-26 15:17

from django.db import migrations, models


def mark_manual_pricing_services(apps, schema_editor):
    Service = apps.get_model("orders", "Service")
    ServiceOrderItem = apps.get_model("orders", "ServiceOrderItem")

    manual_service_name = "Inne / indywidualna diagnoza"
    Service.objects.filter(name=manual_service_name).update(
        pricing_mode="MANUAL_AFTER_DIAGNOSIS",
        base_price_min=0,
        base_price_max=0,
        base_duration_minutes=0,
    )
    ServiceOrderItem.objects.filter(service_name_snapshot=manual_service_name).update(
        pricing_mode_snapshot="MANUAL_AFTER_DIAGNOSIS",
        base_price_min_snapshot=0,
        base_price_max_snapshot=0,
        calculated_price_min=0,
        calculated_price_max=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_auditlog_action_serviceorderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_mode',
            field=models.CharField(choices=[('CONFIGURABLE', 'Wycena z konfiguratora'), ('MANUAL_AFTER_DIAGNOSIS', 'Wycena po diagnozie')], db_index=True, default='CONFIGURABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='serviceorderitem',
            name='pricing_mode_snapshot',
            field=models.CharField(choices=[('CONFIGURABLE', 'Wycena z konfiguratora'), ('MANUAL_AFTER_DIAGNOSIS', 'Wycena po diagnozie')], default='CONFIGURABLE', max_length=30),
        ),
        migrations.RunPython(mark_manual_pricing_services, migrations.RunPython.noop),
    ]
