# Generated by Django 6.0.1 on 2026-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_service_pricing_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('STATUS_CHANGED', 'Zmiana statusu'), ('COMMENT_ADDED', 'Dodanie komentarza'), ('ESTIMATE_SET', 'Ustawienie planowanego terminu'), ('ORDER_CANCELED', 'Anulowanie zlecenia'), ('ORDER_CREATED', 'Utworzenie zlecenia'), ('DIAGNOSIS_UPDATED', 'Aktualizacja diagnozy'), ('REPAIR_ACCEPTED', 'Akceptacja naprawy'), ('TECHNICIAN_ASSIGNED', 'Przypisanie technika'), ('ATTACHMENT_ADDED', 'Dodanie załącznika')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='estimated_completion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planowany termin realizacji'),
        ),
    ]
