# Generated by Django 6.0.1 on 2026-05-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_serviceordercomment_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'wpis historii zmian', 'verbose_name_plural': 'Historia zmian'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'usługa', 'verbose_name_plural': 'Usługi'},
        ),
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'verbose_name': 'opcja usługi', 'verbose_name_plural': 'Opcje usług'},
        ),
        migrations.AlterModelOptions(
            name='serviceoptiongroup',
            options={'verbose_name': 'grupa opcji usługi', 'verbose_name_plural': 'Grupy opcji usług'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'zlecenie serwisowe', 'verbose_name_plural': 'Zlecenia serwisowe'},
        ),
        migrations.AlterModelOptions(
            name='serviceorderattachment',
            options={'verbose_name': 'załącznik do zlecenia', 'verbose_name_plural': 'Załączniki do zleceń'},
        ),
        migrations.AlterModelOptions(
            name='serviceordercomment',
            options={'verbose_name': 'komentarz do zlecenia', 'verbose_name_plural': 'Komentarze do zleceń'},
        ),
        migrations.AlterModelOptions(
            name='serviceorderitem',
            options={'verbose_name': 'pozycja zlecenia', 'verbose_name_plural': 'Pozycje zleceń'},
        ),
        migrations.AlterModelOptions(
            name='serviceorderitemoption',
            options={'verbose_name': 'wybrana opcja zlecenia', 'verbose_name_plural': 'Wybrane opcje zleceń'},
        ),
    ]
