# Generated by Django 6.0.1 on 2026-05-31 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_polish_admin_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'verbose_name': 'odpowiedź do wyboru', 'verbose_name_plural': 'Odpowiedzi do wyboru'},
        ),
        migrations.AlterModelOptions(
            name='serviceoptiongroup',
            options={'verbose_name': 'pytanie w formularzu', 'verbose_name_plural': 'Pytania w formularzu'},
        ),
    ]
